version: '3.5'
services:
    php:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: test_php
        volumes:
            - ./project:/var/www:cached
        links:
#            - mysql
            - postgres
            - redis


    nginx:
        build: ./docker/nginx
        container_name: test_nginx
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./project:/var/www:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

        ports:
            - "80:80"
        links:
            - php

#    mysql:
#        image: mysql:8.0.29
#        restart: always
#        volumes:
#          - ./tmp/db:/var/lib/mysql
#        environment:
#            MYSQL_DATABASE: simple_shop_symfony
#            MYSQL_ROOT_PASSWORD: 123654789
#        ports:
#            - 3306:3306
#        container_name: test_mysql

    redis:
        image: redis
        container_name: test1_redis
        ports:
            - "6382:6379"
        volumes:
            - ./tmp/redis:/data

    postgres:
        image: postgres
        container_name: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: test_postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: root@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root